### PR TITLE
Implement WebAudio client and sinks

### PR DESCRIPTION
**Pull request by skyrangelovv**
Summary: Implement WebAudio client and sinks
Type: Feature
Owner: Vladimir Rangelov
Reviewers: Adam Czynszak, Luke Williamson
Coding Standard Applied: Y
Test Plan: None
Dependencies and Impacts: None
Jira: RIALTO-54

### CODE REVIEW

File: source/GStreamerWebAudioPlayerClient.cpp [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+        [&]()
+        {
+            if (mIsOpen)
+            {
+                if (mSampleDataBuffer.size())
+                {
+                    pushSamples();
+                }
+                m_pushSamplesTimer.cancel();
+                result = mClientBackend->setEos();
```
Comment (skywilliamsonl) [inline source/GStreamerWebAudioPlayerClient.cpp:218]: What if we cant push all the samples here? We don't want to be setting eos until mSampleDataBuffer is empty.

File: source/RialtoGSteamerPlugin.cpp [hunk 2]
```diff
@@ -42,7 +43,8 @@ static gboolean rialto_mse_sinks_init(GstPlugin *plugin)
     GST_INFO("Registering plugins with rank %u", sinkRank);
 
     return gst_element_register(plugin, "rialtomsevideosink", sinkRank, RIALTO_TYPE_MSE_VIDEO_SINK) &&
-           gst_element_register(plugin, "rialtomseaudiosink", sinkRank, RIALTO_TYPE_MSE_AUDIO_SINK);
+           gst_element_register(plugin, "rialtomseaudiosink", sinkRank, RIALTO_TYPE_MSE_AUDIO_SINK) &&
+           gst_element_register(plugin, "rialtouiaudiosink", sinkRank, RIALTO_TYPE_WEB_AUDIO_SINK);
```
Comment (skywilliamsonl) [inline source/RialtoGSteamerPlugin.cpp:47]: change to rialtowebaudiosink

File: source/GStreamerWebAudioPlayerClient.cpp [hunk 3]
```diff
@@ -0,0 +1,339 @@
...
+    if (!mIsOpen || mSampleDataBuffer.empty())
+    {
+        return;
+    }
+
+    uint32_t availableFrames = 0u;
+    if (mClientBackend->getBufferAvailable(availableFrames))
+    {
+        auto dataToPush = std::min(availableFrames * 4, mSampleDataBuffer.size());
+        if ((dataToPush >= 0))
```
Comment (aczs) [inline source/GStreamerWebAudioPlayerClient.cpp:262]: Any point of entering this if clause when dataToPush == 0?

File: source/GStreamerWebAudioPlayerClient.cpp [hunk 4]
```diff
@@ -0,0 +1,339 @@
...
+        {
+            if (mClientBackend->writeBuffer(dataToPush / 4, mSampleDataBuffer.data()))
+            {
+                // remove pushed data from mSampleDataBuffer
+                if (dataToPush < mSampleDataBuffer.size())
+                {
+                    // to compact the memory copy everything to a new vector and swap.
+                    std::vector<uint8_t>(mSampleDataBuffer.begin() + dataToPush, mSampleDataBuffer.end())
```
Comment (aczs) [inline source/GStreamerWebAudioPlayerClient.cpp:270]: It might have quite big impact on performance in some bad scenarios, right?
Wouldn't it be more efficient to use std::queue or mSampleDataBuffer and create new temporary vector, which would be passed to writeBuffer?
Or change API of writeBuffer to pass readonly std::queue?

**Comment by skywilliamsonl** [comment]
FYI you also have a build failure:

| In file included from /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-dunfell/EXEC_0/components/opensource/rialto-gstreamer/source/GStreamerWebAudioPlayerClient.h:23,
|                  from /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-dunfell/EXEC_0/components/opensource/rialto-gstreamer/source/RialtoGStreamerWebAudioSink.h:21,
|                  from /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-dunfell/EXEC_0/components/opensource/rialto-gstreamer/source/RialtoGSteamerPlugin.cpp:21:
| /home/jenkins/jenkinsroot/workspace/build-rpi-hybrid-wpe-dunfell/EXEC_0/components/opensource/rialto-gstreamer/source/WebAudioClientBackendInterface.h:20:10: fatal error: IWebAudioPlayerClient.h: No such file or directory
|    20 | #include <IWebAudioPlayerClient.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

**Comment by jamcoole** [comment]
The build is failing to include the headers added in https://github.com/rdkcentral/rialto/pull/44 because the following file https://github.com/rdkcentral/rialto/blob/master/media/public/CMakeLists.txt is missing them so they are not made available in the include path for rialto-gstreamer 

note once you add these there are then new build failures to address

**Comment by jamcoole** [comment]
please ignore the bcmref va sanity failure this is a known issue https://jira.rdkcentral.com/jira/browse/BCM72180-255

**Review by aczs — APPROVED** [review]

**Review by skywilliamsonl — APPROVED** [review]
